version: '3.9'

services:
  desafio-5-usuario:
    image: postgres:17.5

    container_name: desafio-5-usuario

    restart: unless-stopped

    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - ./desafio5/postgres:/var/lib/postgresql/data

  desafio-5-admin:
    image: dpage/pgadmin4:6.20

    container_name: desafio-5-admin

    restart: unless-stopped

    environment: 
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}

    ports:
      - "5050:80"

    volumes:
      - ./desafio5/pgadmin:/var/lib/pgadmin