version: '3.9'

services:
  desafio-4:
    image: mysql:8.4
    container_name: desafio-4
    restart: unless-stopped
    environment: 
      MYSQL_ROOT_PASSWORD: teste
      MYSQL_DATABASE: banco_desafio4
      MYSQL_USER: Jorge
      MYSQL_PASSWORD: teste
    ports:
      - "3306:3306"
    volumes:
      - ./desafio4:/var/lib/mysql
